API_KEYS = []

TOKEN_LIMIT_SAFETY_FACTOR = 0.8
DEFAULT_FALLBACK_TOKEN_LIMIT = 250_000
DEFAULT_RETRY_DELAY_SECONDS = 10
MAX_RETRIES_WITH_DELAY_PER_KEY = 3

# New constants for Interest ID step
DEFAULT_OUTPUT_TOKENS_INTEREST_ID = 65536
TOKEN_BUDGET_SAFETY_MARGIN_INTEREST_ID = (
    50  # Small safety buffer for interest ID snippet budget
)

# Thinking budgets (conceptual, subtracted from available tokens)
THINKING_BUDGET_INTEREST_ID = 24576
THINKING_BUDGET_MAIN_LLM = 24576 // 2

PLOT_FIG_WIDTH = 400
PLOT_NBINS = 600
FIXED_MODEL_NAME_GEMINI_FLASH = "gemini-2.5-flash-preview-05-20"
