#!/bin/bash
#=========================================================================================
#
# This script manages a grid search experiment:
#   1. Submits the Slurm job array using a specified grid search script.
#   2. Uses the '--wait' flag to pause execution until all batch jobs are complete.
#   3. Aggregates the 'summary.csv' files generated by each job.
#   4. Prints a formatted summary table of all results.
#
#=========================================================================================

set -e # Exit immediately on error

# Define the base directory where results are stored.
# This must match the directory used in run_grid_search.sh
RESULTS_BASE_DIR="TSPulse2/grid_search_results_2080ti"
SLURM_SCRIPT="TSPulse2/run_grid_search.sh"
AGGREGATED_RESULTS_FILE="grid_search_summary.csv"

# --- 1. Submit Slurm Job and Wait ---
echo "Submitting Slurm job array from '${SLURM_SCRIPT}'..."
echo "This script will wait until all jobs have finished."
echo "You can detach this terminal; the process will continue on the server."
echo "--------------------------------------------------------------------"

# The --wait flag is critical. It makes sbatch block until the job completes.
sbatch --wait "${SLURM_SCRIPT}"

echo "--------------------------------------------------------------------"
echo "All Slurm jobs have completed."


# --- 2. Aggregate Results ---
echo "Aggregating results from all model runs..."

# Check if the results directory exists
if [ ! -d "$RESULTS_BASE_DIR" ]; then
    echo "Error: Results directory not found at '${RESULTS_BASE_DIR}'"
    exit 1
fi

# Create the final report file and add a header
echo "Model,CV Accuracy,Final Uni Acc,Final Multi Acc" > "${AGGREGATED_RESULTS_FILE}"

# Use 'find' to locate all the summary.csv files produced by the Python script.
# The '+' in '-exec cat {} +' is efficient, concatenating all files in one go.
find "${RESULTS_BASE_DIR}" -type f -name "summary.csv" -exec cat {} + >> "${AGGREGATED_RESULTS_FILE}"

# --- 3. Print Summary Table ---
echo "Aggregation complete."
echo "Final results stored in '${AGGREGATED_RESULTS_FILE}'"
echo ""
echo "=========================== GRID SEARCH PERFORMANCE SUMMARY ==========================="
# Use 'column' to format the CSV into a nicely aligned table for display
column -t -s, "${AGGREGATED_RESULTS_FILE}"
echo "======================================================================================"
echo ""
echo "For per-series details, inspect the 'detailed_performance_report_*.csv' files"
echo "located inside each model's subdirectory within '${RESULTS_BASE_DIR}'." 